### ISSUE TITLE
Exception log spam on HA restart

### ISSUE THREAD

**Issue by dakahler** [net-daemon/netdaemon#820] opened 2022-12-22 18:33 UTC
## The problem

There is a fair bit of exception spam in the log when rebooting HA:

`[09:33:40 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to home assistant closed the connection, connect retry in 30 seconds
[09:33:40 DBG] NetDaemon.Client.IHomeAssistantRunner: Client disconnected, retrying in 30 seconds...
[09:34:10 DBG] NetDaemon.Client.IHomeAssistantClient: Connecting to Home Assistant websocket on ws://supervisor/core/websocket
[09:34:10 DBG] NetDaemon.Client.IHomeAssistantClient: Error connecting to Home Assistant
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
[09:34:10 DBG] NetDaemon.Client.IHomeAssistantRunner: Error running HassClient
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
   at NetDaemon.Client.Internal.HomeAssistantRunner.InternalRunAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, TimeSpan timeout, CancellationToken cancelToken)
[09:34:10 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to unknown error, set loglevel to debug to view details, connect retry in 30 seconds
[09:34:10 DBG] NetDaemon.Client.IHomeAssistantRunner: Client disconnected, retrying in 30 seconds...
[09:34:40 DBG] NetDaemon.Client.IHomeAssistantClient: Connecting to Home Assistant websocket on ws://supervisor/core/websocket
[09:34:40 DBG] NetDaemon.Client.IHomeAssistantClient: Error connecting to Home Assistant
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
[09:34:40 DBG] NetDaemon.Client.IHomeAssistantRunner: Error running HassClient
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
   at NetDaemon.Client.Internal.HomeAssistantRunner.InternalRunAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, TimeSpan timeout, CancellationToken cancelToken)
[09:34:40 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to unknown error, set loglevel to debug to view details, connect retry in 30 seconds
[09:34:40 DBG] NetDaemon.Client.IHomeAssistantRunner: Client disconnected, retrying in 30 seconds...
[09:35:10 DBG] NetDaemon.Client.IHomeAssistantClient: Connecting to Home Assistant websocket on ws://supervisor/core/websocket
[09:35:10 DBG] NetDaemon.Client.IHomeAssistantClient: Error connecting to Home Assistant
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
[09:35:10 DBG] NetDaemon.Client.IHomeAssistantRunner: Error running HassClient
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '502' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
   at NetDaemon.Client.Internal.HomeAssistantRunner.InternalRunAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, TimeSpan timeout, CancellationToken cancelToken)
[09:35:10 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to unknown error, set loglevel to debug to view details, connect retry in 30 seconds
[09:35:10 DBG] NetDaemon.Client.IHomeAssistantRunner: Client disconnected, retrying in 30 seconds...
[09:35:40 DBG] NetDaemon.Client.IHomeAssistantClient: Connecting to Home Assistant websocket on ws://supervisor/core/websocket
[09:35:40 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant`

## Environment

- NetDaemon release with the issue: 22.50.1
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):

`Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest`

- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by FrankBakkerNl** [comment] 2022-12-27 15:56
Looks like these are debug and information log entries. If you are not interested in these you could lower your logging level, or send them to a different file / location.

**Comment by helto4real** [comment] 2022-12-29 08:02
Yea the debug level is there so we can do detailed analysis of errors. Normal log-level for running ND is `information`. I will close this as "by design"

**Closed by helto4real** 2022-12-29 08:02 UTC
