### ISSUE TITLE
when custom code in c#crashes, netdaemon try to add a new listener but port is busy

### ISSUE THREAD

**Issue by quettih** [net-daemon/netdaemon#328] opened 2021-02-25 18:28 UTC
## The problem
  when a custom code crashes, netdaemon tries to restart a listener but it is already opened.
I use the configuration where my dll are compiled and published to netdaemon. I don't use code in CS file but the "solution" approach

## Environment
- NetDaemon release with the issue:  21.08.1
- Last working NetDaemon release (if known): N/A
- Operating environment (Home assistant Add-on/Docker/Dev setup):  RPI 4 Home Assistant Core 2021.2.3 (it is old I  know)
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#
   public override void Initialize()
        {
       register for state change to execute a procedure
       foreach (var item in States)
            {
               curr_ent.StateChanges.Subscribe(s => m2r_ProgramSelector(  item.EntityId   ));
            }

}

 private async void m2r_ProgramSelector(string entity_id)
 {
    int xx = Convert.ToInt32("crash");

}

```

## Traceback/Error logs
I turnoff my entity and the sensor fires the state change.
my sw crashes and netdaemon restart and  happen    Listen method has been called more than once without closing.
![unknown](https://user-images.githubusercontent.com/34207189/109199062-4836fa00-779f-11eb-907a-77f7d3fd61a7.png)

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
Starting NetDaemon Runner
Starting NetDaemon Admin
Warning: you are using a custom daemon, this can potentially be unsecure. Please review your security. To remove this warning, set NETDAEMON__WARN_IF_CUSTOM_APP_SOURCE=false 
[services.d] done.
Run the custom daemon at /config/netdaemon/M2RHA.dll..
 Running custom pre-compiled daemon...
[19:22:57 INF] Starting NeDaemon service (version 21.05.1)...
[19:22:59 WRN] No NetDaemon integration found, please consider installing the companion integration for more features. See https://netdaemon.xyz/docs/started/integration for details.
[19:22:59 INF] Successfully connected to Home Assistant Core in Home Assistant Add-on
[19:22:59 DBG] Loading local assembly apps...
[19:22:59 DBG] New websocket client 01e6b18c-52d8-4416-86df-f2824fdde0e8
Admin GUI: Running NetDaemon Admin
[19:23:00 DBG] Found total of 4 apps
[19:23:00 DBG] Startup: persistentapp_persistent_app
[19:23:00 DBG] Startup: m2r_main_m2r_main
[19:23:00 INF] Successfully loaded app persistent_app (PersistentApp)
[19:23:00 INF]   M2R_Main: Initialize started!
[19:23:00 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_management
[19:23:00 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_management_2
[19:23:00 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_2
[19:23:00 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power
[19:23:00 INF]   M2R_Main: Initialize completed!
[19:23:00 INF] Successfully loaded app M2R_Main (M2R_Main)
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at M2RHA.apps.M2RHA.M2R_Main.m2r_ProgramSelector(String entity_id, Context cnt) in h:\lavoro\__M2R\HomeAssistant\NetDaemon\M2RHA_DEV-qh\M2RHA\apps\M2RHA\M2R_Main.cs:line 114
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Admin GUI: Reconnect will be attempted in 10 seconds. 
Starting NetDaemon Runner
Warning: you are using a custom daemon, this can potentially be unsecure. Please review your security. To remove this warning, set NETDAEMON__WARN_IF_CUSTOM_APP_SOURCE=false 
Run the custom daemon at /config/netdaemon/M2RHA.dll..
 Running custom pre-compiled daemon...
[19:23:28 INF] Starting NeDaemon service (version 21.05.1)...
[19:23:30 WRN] No NetDaemon integration found, please consider installing the companion integration for more features. See https://netdaemon.xyz/docs/started/integration for details.
[19:23:30 INF] Successfully connected to Home Assistant Core in Home Assistant Add-on
[19:23:30 DBG] Loading local assembly apps...
[19:23:31 DBG] Found total of 4 apps
[19:23:31 DBG] Startup: persistentapp_persistent_app
[19:23:31 DBG] Startup: m2r_main_m2r_main
[19:23:31 INF]   M2R_Main: Initialize started!
[19:23:31 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power
[19:23:31 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_management
[19:23:31 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_management_2
[19:23:31 INF]   M2R_Main:    Subscribe program for entity: sensor.aeotec_limited_zw175_smart_switch_7_power_2
[19:23:31 INF]   M2R_Main: Initialize completed!
[19:23:31 INF] Successfully loaded app M2R_Main (M2R_Main)
[19:23:31 INF] Successfully loaded app persistent_app (PersistentApp)
[19:23:38 DBG] New websocket client 625cedd9-a5bf-440b-b30e-94157d0fc75d
net.js:1366
    throw new ERR_SERVER_ALREADY_LISTEN();
    ^
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1366:11)
    at WebSocket.ws.onopen (/admin/host/admin.js:35:12)
    at WebSocket.onOpen (/admin/node_modules/ws/lib/event-target.js:144:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.setSocket (/admin/node_modules/ws/lib/websocket.js:177:10)
    at ClientRequest.req.on (/admin/node_modules/ws/lib/websocket.js:671:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnData (_http_client.js:484:11)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
Starting NetDaemon Admin
```

**Comment by helto4real** [comment] 2021-03-16 15:34
Thanks, good find. Thanks for reporting

**Comment by helto4real** [comment] 2021-04-24 15:53
Think the problem is now when I looked closer to the code that you are calling async code from subscribe. That is a anti-pattern that could cause all sorts of potential issues.

**Comment by helto4real** [comment] 2021-05-02 13:42
Closing, please re-open if you still experience problems after my suggestion

**Closed by helto4real** 2021-05-02 13:42 UTC
